name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: ruby-${{ matrix.ruby }} rails-${{ matrix.rails }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
        rails:
          - '5.2'
          - '6.0'
          - '6.1'
          - '7.0'
        exclude:
          - ruby: '2.6'
            rails: '7.0'
          - ruby: '3.0'
            rails: '5.2'
          - ruby: '3.1'
            rails: '5.2'
          - ruby: '3.2'
            rails: '5.2'
          - ruby: '3.2'
            rails: '6.0'
          - ruby: '3.2'
            rails: '6.1'
    env:
      BUNDLE_JOBS: 4
      BUNDLE_PATH: vendor/bundle
      MYSQL_PASSWORD: root
      RAILS_VERSION: ${{ matrix.rails }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update packages
        run: sudo apt-get update
      - name: Install Sqlite
        run: sudo apt-get install libsqlite3-dev -y
        if: matrix.database == 'sqlite3'
      - id: cache-bundler
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ matrix.ruby }}-${{ matrix.rails }}-${{ hashFiles('mobility-ransack.gemspec') }}-${{ hashFiles('Gemfile') }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install latest Bundler
        run: gem install bundler --no-document
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
